### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by TibebeJS** [abdimk/Graphene#2]
Hello, I've seen the project and it's fantastic! Good Job on that. 

Here are my suggestions on somethings you may want to improve on.. 
- there are no `requirements.txt` file, `Pipfile` or the like found in the repo which makes it hard to know and install the dependencies (checkout https://stackoverflow.com/questions/31684375/automatically-create-requirements-txt)
- update the `README`  (how to get started, what does it look like, etc..)
- the `.gitignore` file you have used is of a `php` project (I've created a pull-request that fixes that)

But overall, it's a  neat design/project :+1:

**Comment by abdimk** [comment]
first I wanted to say thanks but dude this is pre release I didn't even organized the code I will do that soon 
I put all the files in the main.py which is a bad practice 

I will make a major change to it Thanks please star the project it you think its help full
